# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vidhipatel/starry

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vidhipatel/starry

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vidhipatel/starry/CMakeFiles /home/vidhipatel/starry//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vidhipatel/starry/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named starry

# Build rule for target.
starry: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 starry
.PHONY : starry

# fast build rule for target.
starry/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/build
.PHONY : starry/fast

src/Layer.o: src/Layer.cpp.o
.PHONY : src/Layer.o

# target to build an object file
src/Layer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Layer.cpp.o
.PHONY : src/Layer.cpp.o

src/Layer.i: src/Layer.cpp.i
.PHONY : src/Layer.i

# target to preprocess a source file
src/Layer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Layer.cpp.i
.PHONY : src/Layer.cpp.i

src/Layer.s: src/Layer.cpp.s
.PHONY : src/Layer.s

# target to generate assembly for a file
src/Layer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Layer.cpp.s
.PHONY : src/Layer.cpp.s

src/Matrix.o: src/Matrix.cpp.o
.PHONY : src/Matrix.o

# target to build an object file
src/Matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Matrix.cpp.o
.PHONY : src/Matrix.cpp.o

src/Matrix.i: src/Matrix.cpp.i
.PHONY : src/Matrix.i

# target to preprocess a source file
src/Matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Matrix.cpp.i
.PHONY : src/Matrix.cpp.i

src/Matrix.s: src/Matrix.cpp.s
.PHONY : src/Matrix.s

# target to generate assembly for a file
src/Matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Matrix.cpp.s
.PHONY : src/Matrix.cpp.s

src/Neuron.o: src/Neuron.cpp.o
.PHONY : src/Neuron.o

# target to build an object file
src/Neuron.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Neuron.cpp.o
.PHONY : src/Neuron.cpp.o

src/Neuron.i: src/Neuron.cpp.i
.PHONY : src/Neuron.i

# target to preprocess a source file
src/Neuron.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Neuron.cpp.i
.PHONY : src/Neuron.cpp.i

src/Neuron.s: src/Neuron.cpp.s
.PHONY : src/Neuron.s

# target to generate assembly for a file
src/Neuron.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/Neuron.cpp.s
.PHONY : src/Neuron.cpp.s

src/neuralNetwork/BackPropagation.o: src/neuralNetwork/BackPropagation.cpp.o
.PHONY : src/neuralNetwork/BackPropagation.o

# target to build an object file
src/neuralNetwork/BackPropagation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/BackPropagation.cpp.o
.PHONY : src/neuralNetwork/BackPropagation.cpp.o

src/neuralNetwork/BackPropagation.i: src/neuralNetwork/BackPropagation.cpp.i
.PHONY : src/neuralNetwork/BackPropagation.i

# target to preprocess a source file
src/neuralNetwork/BackPropagation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/BackPropagation.cpp.i
.PHONY : src/neuralNetwork/BackPropagation.cpp.i

src/neuralNetwork/BackPropagation.s: src/neuralNetwork/BackPropagation.cpp.s
.PHONY : src/neuralNetwork/BackPropagation.s

# target to generate assembly for a file
src/neuralNetwork/BackPropagation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/BackPropagation.cpp.s
.PHONY : src/neuralNetwork/BackPropagation.cpp.s

src/neuralNetwork/FeedForward.o: src/neuralNetwork/FeedForward.cpp.o
.PHONY : src/neuralNetwork/FeedForward.o

# target to build an object file
src/neuralNetwork/FeedForward.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/FeedForward.cpp.o
.PHONY : src/neuralNetwork/FeedForward.cpp.o

src/neuralNetwork/FeedForward.i: src/neuralNetwork/FeedForward.cpp.i
.PHONY : src/neuralNetwork/FeedForward.i

# target to preprocess a source file
src/neuralNetwork/FeedForward.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/FeedForward.cpp.i
.PHONY : src/neuralNetwork/FeedForward.cpp.i

src/neuralNetwork/FeedForward.s: src/neuralNetwork/FeedForward.cpp.s
.PHONY : src/neuralNetwork/FeedForward.s

# target to generate assembly for a file
src/neuralNetwork/FeedForward.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/FeedForward.cpp.s
.PHONY : src/neuralNetwork/FeedForward.cpp.s

src/neuralNetwork/Network.o: src/neuralNetwork/Network.cpp.o
.PHONY : src/neuralNetwork/Network.o

# target to build an object file
src/neuralNetwork/Network.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/Network.cpp.o
.PHONY : src/neuralNetwork/Network.cpp.o

src/neuralNetwork/Network.i: src/neuralNetwork/Network.cpp.i
.PHONY : src/neuralNetwork/Network.i

# target to preprocess a source file
src/neuralNetwork/Network.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/Network.cpp.i
.PHONY : src/neuralNetwork/Network.cpp.i

src/neuralNetwork/Network.s: src/neuralNetwork/Network.cpp.s
.PHONY : src/neuralNetwork/Network.s

# target to generate assembly for a file
src/neuralNetwork/Network.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/Network.cpp.s
.PHONY : src/neuralNetwork/Network.cpp.s

src/neuralNetwork/SetErrors.o: src/neuralNetwork/SetErrors.cpp.o
.PHONY : src/neuralNetwork/SetErrors.o

# target to build an object file
src/neuralNetwork/SetErrors.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/SetErrors.cpp.o
.PHONY : src/neuralNetwork/SetErrors.cpp.o

src/neuralNetwork/SetErrors.i: src/neuralNetwork/SetErrors.cpp.i
.PHONY : src/neuralNetwork/SetErrors.i

# target to preprocess a source file
src/neuralNetwork/SetErrors.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/SetErrors.cpp.i
.PHONY : src/neuralNetwork/SetErrors.cpp.i

src/neuralNetwork/SetErrors.s: src/neuralNetwork/SetErrors.cpp.s
.PHONY : src/neuralNetwork/SetErrors.s

# target to generate assembly for a file
src/neuralNetwork/SetErrors.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/SetErrors.cpp.s
.PHONY : src/neuralNetwork/SetErrors.cpp.s

src/neuralNetwork/Train.o: src/neuralNetwork/Train.cpp.o
.PHONY : src/neuralNetwork/Train.o

# target to build an object file
src/neuralNetwork/Train.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/Train.cpp.o
.PHONY : src/neuralNetwork/Train.cpp.o

src/neuralNetwork/Train.i: src/neuralNetwork/Train.cpp.i
.PHONY : src/neuralNetwork/Train.i

# target to preprocess a source file
src/neuralNetwork/Train.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/Train.cpp.i
.PHONY : src/neuralNetwork/Train.cpp.i

src/neuralNetwork/Train.s: src/neuralNetwork/Train.cpp.s
.PHONY : src/neuralNetwork/Train.s

# target to generate assembly for a file
src/neuralNetwork/Train.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/neuralNetwork/Train.cpp.s
.PHONY : src/neuralNetwork/Train.cpp.s

src/train.o: src/train.cpp.o
.PHONY : src/train.o

# target to build an object file
src/train.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/train.cpp.o
.PHONY : src/train.cpp.o

src/train.i: src/train.cpp.i
.PHONY : src/train.i

# target to preprocess a source file
src/train.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/train.cpp.i
.PHONY : src/train.cpp.i

src/train.s: src/train.cpp.s
.PHONY : src/train.s

# target to generate assembly for a file
src/train.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/train.cpp.s
.PHONY : src/train.cpp.s

src/utils/math.o: src/utils/math.cpp.o
.PHONY : src/utils/math.o

# target to build an object file
src/utils/math.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/utils/math.cpp.o
.PHONY : src/utils/math.cpp.o

src/utils/math.i: src/utils/math.cpp.i
.PHONY : src/utils/math.i

# target to preprocess a source file
src/utils/math.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/utils/math.cpp.i
.PHONY : src/utils/math.cpp.i

src/utils/math.s: src/utils/math.cpp.s
.PHONY : src/utils/math.s

# target to generate assembly for a file
src/utils/math.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/utils/math.cpp.s
.PHONY : src/utils/math.cpp.s

src/utils/misc.o: src/utils/misc.cpp.o
.PHONY : src/utils/misc.o

# target to build an object file
src/utils/misc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/utils/misc.cpp.o
.PHONY : src/utils/misc.cpp.o

src/utils/misc.i: src/utils/misc.cpp.i
.PHONY : src/utils/misc.i

# target to preprocess a source file
src/utils/misc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/utils/misc.cpp.i
.PHONY : src/utils/misc.cpp.i

src/utils/misc.s: src/utils/misc.cpp.s
.PHONY : src/utils/misc.s

# target to generate assembly for a file
src/utils/misc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/starry.dir/build.make CMakeFiles/starry.dir/src/utils/misc.cpp.s
.PHONY : src/utils/misc.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... starry"
	@echo "... src/Layer.o"
	@echo "... src/Layer.i"
	@echo "... src/Layer.s"
	@echo "... src/Matrix.o"
	@echo "... src/Matrix.i"
	@echo "... src/Matrix.s"
	@echo "... src/Neuron.o"
	@echo "... src/Neuron.i"
	@echo "... src/Neuron.s"
	@echo "... src/neuralNetwork/BackPropagation.o"
	@echo "... src/neuralNetwork/BackPropagation.i"
	@echo "... src/neuralNetwork/BackPropagation.s"
	@echo "... src/neuralNetwork/FeedForward.o"
	@echo "... src/neuralNetwork/FeedForward.i"
	@echo "... src/neuralNetwork/FeedForward.s"
	@echo "... src/neuralNetwork/Network.o"
	@echo "... src/neuralNetwork/Network.i"
	@echo "... src/neuralNetwork/Network.s"
	@echo "... src/neuralNetwork/SetErrors.o"
	@echo "... src/neuralNetwork/SetErrors.i"
	@echo "... src/neuralNetwork/SetErrors.s"
	@echo "... src/neuralNetwork/Train.o"
	@echo "... src/neuralNetwork/Train.i"
	@echo "... src/neuralNetwork/Train.s"
	@echo "... src/train.o"
	@echo "... src/train.i"
	@echo "... src/train.s"
	@echo "... src/utils/math.o"
	@echo "... src/utils/math.i"
	@echo "... src/utils/math.s"
	@echo "... src/utils/misc.o"
	@echo "... src/utils/misc.i"
	@echo "... src/utils/misc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

